### ISSUE TITLE
Start map on Oct. 2?

### ISSUE THREAD

**Issue by mathisonian** [ParametricPress/01-anything-that-flies-on-anything-that-moves#3]
I'm wondering if its a little weird to start with no headline, and then have the player immediately pause after you click play. Maybe it makes more sense to just start in a state that has the first headline visible? 

@megan-vo

**Comment by megan-vo** [comment]
Ah right -- that makes sense. I bumped it up one to test the functionality but it makes sense to have it start at the beginning. Will fix that soon!

**Comment by megan-vo** [comment]
Fixed!
